apiVersion: v1
kind: Namespace
metadata:
  name: churn-model
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: churn-model
  annotations:
    serving.kserve.io/s3-endpoint: s3.amazonaws.com
    serving.kserve.io/s3-usehttps: "1"
    serving.kserve.io/s3-region: eu-north-1
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "AKIA3G7UQXRQVR6D5FLJ"
  AWS_SECRET_ACCESS_KEY: "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"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-s3-access
  namespace: churn-model
secrets:
- name: s3-secret
